pipeline {
    agent any
     parameters {
        string(defaultValue: "", description: 'What environment?', name: 'Environment')
        // choices are newline 
        choice(choices: 'US-EAST-1\nUS-WEST-2', description: 'What AWS region?', name: 'region')
    }
    tools {
        maven 'maven'
        jdk 'JAVA1.8'
    }
    stages {
        stage ('Checkout'){
            steps 
            {
                git (
                    url: 'https://github.com/SankararaoVana/Devops.git',
                    credentialsId: 'b368d303-fea8-4cea-8f31-a38574483751'
                )
            }
            
            }
    }
}
